# Generated by Django 4.1.7 on 2023-10-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Year',
            new_name='year',
        ),
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=14, upload_to='gallary'),
            preserve_default=False,
        ),
    ]
